### ISSUE TITLE
Improve 'Test using a Mock implementation' challenge episode 3.3

### ISSUE THREAD

**Issue by mhagdorn** [carpentries-incubator/python-intermediate-development#367]
The ['Test using a Mock implementation'](https://carpentries-incubator.github.io/python-intermediate-development/33-code-decoupling-abstractions/index.html#exercise-test-using-a-mock-implementation) challenge needs a few improvements:

```[tasklist]
### Tasks
- [ ] The analyse_data function has not yet been fully refactored, it still contains the plot production and doesn't return anything
- [ ] Mention that the failing of the test is expected and that we will adapt the `analyse_data` function to return an array in the [next episode]( https://carpentries-incubator.github.io/python-intermediate-development/34-code-refactoring/index.html#exercise-write-regression-tests)
- [ ] Make it explicit that you should create a new test module in the `test` folder called `test_compute_data.py`, because the function we are testing is in `compute_data.py`
```

**Comment by svenvanderburg** [comment]
We should mention that the failing of the test is expected and that we will adapt the `analyse_data` function to return an array in the next episode: https://carpentries-incubator.github.io/python-intermediate-development/34-code-refactoring/index.html#exercise-write-regression-tests

**Comment by svenvanderburg** [comment]
Proposed fix https://github.com/esciencecenter-digital-skills/python-intermediate-development-gitlab/pull/8/commits/9a1bbec1bb1ba42ed0bae3499be3ca6d8c1aeed0 (which is slightly different from the task list above, but I think this works better)

**Comment by steve-crouch** [comment]
@svenvanderburg 's proposed alternative solution seems to flow better as a first step prior to refactoring the code later, whilst addressing the spirit of the main points above,
