### ISSUE TITLE
Notify contributors about transition to Carpentries Workbench

### ISSUE THREAD

**Issue by bielsnohr** [carpentries-incubator/python-intermediate-development#384]
As agreed in a chat with @anenadic : 

```[tasklist]
### Tasks
- [ ] We will attempt to get current set of PRs merged in or resolved
- [ ] Any other contributions will be put aside until we go through the template conversion
- [ ] There will be a freeze while the conversion is taking place (around CarpentryConnect)
- [ ] It would be good to send a message to various TopicBox mailing lists to notify people about this
- [x] Also perhaps a message somewhere on this repo (see #391)
- [ ] See if there is a way to notify forks of upcoming changes
```
